########################################################
#               nEXO OD FLUKA Simulation YAML          #
########################################################

Simulation:
  Muons: 100                 # Number of muons to run for simulation // rewrites the input file
  MakeNewFile: True           # Generate a new batch of muons for the sim? False -> Use the previous batch
  ScoreOD: True              # If True, it counts neutrons in the OD, if False, counts neutrons in TPC
  Repititions: 2              # How many times should we repeat this sim? (new muons if MakeNewFile == True)

Output:
  OutputDir: './Jan2023/'
  NeutronFile: 'fluka_data.hdf5'
  ProgressOut: 'fluka_sim_sum.txt'

Input:                        # Not likely to require changing
  InputPath: '/gpfs/slac/staas/fs1/g/exo/exo_data8/exo_data/users/rross/flukaSims/'
  InputFile: 'nEXO_OD.inp'
  SourceFile: 'muon_from_file.f'
  MGDrawFile: 'mgdraw_neutron_count.f'

Source: # (DON'T CHANGE -unless running locally) For FLUKA binaries in the singularity image 
  FlukaPath: '/usr/local/fluka/bin/'


  

